### ISSUE TITLE
How to test only a single file

### ISSUE THREAD

**Issue by lost22git** [lpil/gleeunit#28]

**Comment by inoas** [comment]
Last time I checked this was not possible. It also was not possible to call the testing software from a function/as a lib. These are the two things I changed in my fork [gleeunit_glacier](https://github.com/inoas/gleeunit/tree/glacier) but it is sadly not up to date with gleam 1.0

**Comment by lpil** [comment]
Hello! Yes this test runner is very simple and does not support that I'm afraid.

**Comment by ryanb** [comment]
@lpil running tests in a specific file/line would be very useful. Even in a small project you may make a change which fails multiple tests and you want to focus on getting one test passing. Or you have slower tests and want to focus on other tests.

Is this an intentional design decision to keep gleeunit simple? Or is it a limitation of Gleam?

**Comment by inoas** [comment]
@ryanb so I have updated glacier_gleeunit and glacier (which uses glacier_gleeunit).

Le me know if that works for you. It does not do file/line but it works per test module:

https://hex.pm/packages/glacier/ for automatically running tests of changed modules/changed test modules
https://hex.pm/packages/glacier_gleeunit for running dedicated test modules

**Comment by ryanb** [comment]
@inoas thanks! How do I run it on a module? I don't see mention of this in [the readme](https://github.com/inoas/gleeunit/tree/glacier?tab=readme-ov-file)

**Comment by lpil** [comment]
Hey @ryanb !

> Is this an intentional design decision to keep gleeunit simple?

We don't have any control over EUnit and this library isn't a good test library, rather it's just a quick wrapper that was made to get us going until someone makes a proper test runner. Unfortunately no one has done this yet, and I'm too busy with other things.

> Or is it a limitation of Gleam?

Gleam doesn't care how you run your tests, the only thing it does is call `APP_test.main` and the rest is up to you.

If you want to run one test you could just call that test from your main function instead of calling gleeunit.

**Comment by inoas** [comment]
@ryanb sorry the info above was a bit missleading, I have edited it, the glacier readme has the info as well: https://github.com/inoas/glacier/blob/main/README.md?plain=1#L60

**Comment by ryanb** [comment]
@inoas awesome thanks! Looks like just what I need. Will have to try this out.
